# Generated by Django 4.0.1 on 2023-07-03 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('employee_name', models.CharField(max_length=255)),
                ('employee_unique_id', models.CharField(max_length=255)),
                ('site_name', models.IntegerField()),
                ('department', models.IntegerField()),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('modified_dt', models.DateTimeField(max_length=500, null=True)),
                ('created_by', models.IntegerField()),
                ('modified_by', models.IntegerField(null=True)),
                ('delete_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=50)),
            ],
            options={
                'db_table': 'payroll_employee',
            },
        ),
    ]
