# Generated by Django 4.0.1 on 2023-07-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_detection_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='emp_images/'),
        ),
    ]
