# Generated by Django 4.0.1 on 2023-07-03 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_detection_app', '0002_employee_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_name',
        ),
    ]
